package ar.edu.unicen.exa.intia.imgProc.mobile.tests.exceptions;

public enum InputExceptionEnum {
	PARAMETROS_DE_ENTRADA_REQUERIDOS,
	ALGORITMOS_TRANSFORMACION_REQUERIDOS,
	ALGORITMOS_EVALUACION_REQUERIDOS,
	IMAGENES_DE_ENTRADA_REQUERIDA,
	ALGORITMO_EVALUACION_INCOMPLETO,
	ALGORITMO_TRANSFORMACION_INCOMPLETO,
	ALGORITMO_TRANSFORMACION_DESCONOCIDO,
	ALGORITMO_TRANSFORMACION_INACCESIBLE,
	ALGORITMO_TRANSFORMACION_CONSTRUCTOR_NO_VISIBLE;
}
